name: hush
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Existing dependencies
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.9.1
  flutter_local_notifications: ^19.2.1
  shared_preferences: ^2.5.3
  provider: ^6.1.5

  # FIXED: Use only RevenueCat for subscriptions (removes conflict)
  purchases_flutter: ^6.30.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true